# This file has been generated by node2nix 1.2.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "material-components-web-0.9.1" = {
      name = "material-components-web";
      packageName = "material-components-web";
      version = "0.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/material-components-web/-/material-components-web-0.9.1.tgz";
        sha1 = "052d02c81f1af2a361568ae95d232e3efd8b6345";
      };
    };
    "material-design-icons-3.0.1" = {
      name = "material-design-icons";
      packageName = "material-design-icons";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/material-design-icons/-/material-design-icons-3.0.1.tgz";
        sha1 = "9a71c48747218ebca51e51a66da682038cdcb7bf";
      };
    };
    "roboto-fontface-0.7.0" = {
      name = "roboto-fontface";
      packageName = "roboto-fontface";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/roboto-fontface/-/roboto-fontface-0.7.0.tgz";
        sha1 = "2f36464e5c99353e8427f55f1fca7be1a8a417d9";
      };
    };
    "@material/animation-0.1.5" = {
      name = "@material/animation";
      packageName = "@material/animation";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/animation/-/animation-0.1.5.tgz";
        sha1 = "79c45ccdcde8a286a4c3d7955873b2079e4e5c32";
      };
    };
    "@material/auto-init-0.1.1" = {
      name = "@material/auto-init";
      packageName = "@material/auto-init";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/auto-init/-/auto-init-0.1.1.tgz";
        sha1 = "16a5c37061be71bdcb7b5abc30f6e9785d58c777";
      };
    };
    "@material/base-0.1.2" = {
      name = "@material/base";
      packageName = "@material/base";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/base/-/base-0.1.2.tgz";
        sha1 = "5cc685eeb3c56fcb13905228aec50f96e2012df7";
      };
    };
    "@material/button-0.3.3" = {
      name = "@material/button";
      packageName = "@material/button";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/button/-/button-0.3.3.tgz";
        sha1 = "6af6041d7db1957691a36fbfa866e82018edb021";
      };
    };
    "@material/card-0.1.7" = {
      name = "@material/card";
      packageName = "@material/card";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/card/-/card-0.1.7.tgz";
        sha1 = "4fe4fca8c8b838e9b786721ca5dee2b63e4a02ee";
      };
    };
    "@material/checkbox-0.3.1" = {
      name = "@material/checkbox";
      packageName = "@material/checkbox";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/checkbox/-/checkbox-0.3.1.tgz";
        sha1 = "60b53d836d213575774a5f296d40cf5e01d7f6ba";
      };
    };
    "@material/dialog-0.2.1" = {
      name = "@material/dialog";
      packageName = "@material/dialog";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/dialog/-/dialog-0.2.1.tgz";
        sha1 = "44fd4cb81cd0364953d09dbad9845c745c36dc3b";
      };
    };
    "@material/drawer-0.3.1" = {
      name = "@material/drawer";
      packageName = "@material/drawer";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/drawer/-/drawer-0.3.1.tgz";
        sha1 = "ae3137e34ecf87f7d8a58e2bc11e88d06e667e80";
      };
    };
    "@material/elevation-0.1.4" = {
      name = "@material/elevation";
      packageName = "@material/elevation";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/elevation/-/elevation-0.1.4.tgz";
        sha1 = "b957e5336ff68b60ca5adee4b25a050e7f5f41aa";
      };
    };
    "@material/fab-0.3.5" = {
      name = "@material/fab";
      packageName = "@material/fab";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/fab/-/fab-0.3.5.tgz";
        sha1 = "62ca12a67cb7f22af815365c4e9c3913660a2d85";
      };
    };
    "@material/form-field-0.2.3" = {
      name = "@material/form-field";
      packageName = "@material/form-field";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/form-field/-/form-field-0.2.3.tgz";
        sha1 = "b788f4af748768577d712dc59b0f07bfa1ccb800";
      };
    };
    "@material/grid-list-0.2.1" = {
      name = "@material/grid-list";
      packageName = "@material/grid-list";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/grid-list/-/grid-list-0.2.1.tgz";
        sha1 = "845e5bb84811f0a384cc1fe680577664e32525a6";
      };
    };
    "@material/icon-toggle-0.1.8" = {
      name = "@material/icon-toggle";
      packageName = "@material/icon-toggle";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/icon-toggle/-/icon-toggle-0.1.8.tgz";
        sha1 = "c2e9b0f2dc76759e3f5d7bc81df254e149071cad";
      };
    };
    "@material/layout-grid-0.1.1" = {
      name = "@material/layout-grid";
      packageName = "@material/layout-grid";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/layout-grid/-/layout-grid-0.1.1.tgz";
        sha1 = "bdfc048c61e32785bd59f77ef4d69ca68f337605";
      };
    };
    "@material/list-0.2.6" = {
      name = "@material/list";
      packageName = "@material/list";
      version = "0.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/list/-/list-0.2.6.tgz";
        sha1 = "6a5d048c93fc78f258e92e23a55a8b2267045201";
      };
    };
    "@material/menu-0.2.3" = {
      name = "@material/menu";
      packageName = "@material/menu";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/menu/-/menu-0.2.3.tgz";
        sha1 = "f03aa09622598bc312025f5d6353bf23582a0cc3";
      };
    };
    "@material/radio-0.2.1" = {
      name = "@material/radio";
      packageName = "@material/radio";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/radio/-/radio-0.2.1.tgz";
        sha1 = "bd74864d6608f0c4fc4a3b313826317e02b6dc3d";
      };
    };
    "@material/ripple-0.5.1" = {
      name = "@material/ripple";
      packageName = "@material/ripple";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/ripple/-/ripple-0.5.1.tgz";
        sha1 = "b361f10d30fd4e6e1db9c5234a0dac32dfe35ce6";
      };
    };
    "@material/select-0.3.3" = {
      name = "@material/select";
      packageName = "@material/select";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/select/-/select-0.3.3.tgz";
        sha1 = "d442b7e8cba9b303e2156f95f78c4ab6cc36d582";
      };
    };
    "@material/snackbar-0.1.8" = {
      name = "@material/snackbar";
      packageName = "@material/snackbar";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/snackbar/-/snackbar-0.1.8.tgz";
        sha1 = "638703c6056d84a9df2531d1057d0870c5902006";
      };
    };
    "@material/switch-0.1.4" = {
      name = "@material/switch";
      packageName = "@material/switch";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/switch/-/switch-0.1.4.tgz";
        sha1 = "ea394aabf28ea019a7db6316617c73ef60eaf7f6";
      };
    };
    "@material/textfield-0.2.6" = {
      name = "@material/textfield";
      packageName = "@material/textfield";
      version = "0.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/textfield/-/textfield-0.2.6.tgz";
        sha1 = "4d2e6afbdf75dc18b458eb67aebfaf6e3c105849";
      };
    };
    "@material/theme-0.1.4" = {
      name = "@material/theme";
      packageName = "@material/theme";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/theme/-/theme-0.1.4.tgz";
        sha1 = "d094bc99eff7535eac4650bacadfc10faaba3792";
      };
    };
    "@material/toolbar-0.2.2" = {
      name = "@material/toolbar";
      packageName = "@material/toolbar";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/toolbar/-/toolbar-0.2.2.tgz";
        sha1 = "1d87d6ba4e5d6cd0010031c151d9f29b5ec949ed";
      };
    };
    "@material/typography-0.2.1" = {
      name = "@material/typography";
      packageName = "@material/typography";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/typography/-/typography-0.2.1.tgz";
        sha1 = "3c5ad4868d52f394746e58abc6788caeb2101fc7";
      };
    };
    "@material/rtl-0.1.3" = {
      name = "@material/rtl";
      packageName = "@material/rtl";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/rtl/-/rtl-0.1.3.tgz";
        sha1 = "87097b0aa7f56c1748a2a3a2edd0463783bfacd5";
      };
    };
    "@material/typography-0.1.1" = {
      name = "@material/typography";
      packageName = "@material/typography";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/typography/-/typography-0.1.1.tgz";
        sha1 = "fb2e3437bd3284d39e9fb91485767ade6b2bd0c1";
      };
    };
    "focus-trap-2.3.0" = {
      name = "focus-trap";
      packageName = "focus-trap";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/focus-trap/-/focus-trap-2.3.0.tgz";
        sha1 = "07c91964867d346315f4f5f8df88bf96455316e2";
      };
    };
    "tabbable-1.0.6" = {
      name = "tabbable";
      packageName = "tabbable";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/tabbable/-/tabbable-1.0.6.tgz";
        sha1 = "7c26a87ea6f4a25edf5edb619745a0ae740724fc";
      };
    };
  };
  args = {
    name = "reflex-material";
    packageName = "reflex-material";
    version = "1.0.0";
    src = builtins.filterSource (path: type: baseNameOf path == "package.json") ./.;
    dependencies = [
      (sources."material-components-web-0.9.1" // {
        dependencies = [
          sources."@material/animation-0.1.5"
          sources."@material/auto-init-0.1.1"
          sources."@material/base-0.1.2"
          sources."@material/button-0.3.3"
          sources."@material/card-0.1.7"
          (sources."@material/checkbox-0.3.1" // {
            dependencies = [
              sources."@material/rtl-0.1.3"
            ];
          })
          (sources."@material/dialog-0.2.1" // {
            dependencies = [
              sources."@material/rtl-0.1.3"
              sources."@material/typography-0.1.1"
              (sources."focus-trap-2.3.0" // {
                dependencies = [
                  sources."tabbable-1.0.6"
                ];
              })
            ];
          })
          (sources."@material/drawer-0.3.1" // {
            dependencies = [
              sources."@material/rtl-0.1.3"
            ];
          })
          sources."@material/elevation-0.1.4"
          sources."@material/fab-0.3.5"
          (sources."@material/form-field-0.2.3" // {
            dependencies = [
              sources."@material/rtl-0.1.3"
            ];
          })
          (sources."@material/grid-list-0.2.1" // {
            dependencies = [
              sources."@material/rtl-0.1.3"
            ];
          })
          sources."@material/icon-toggle-0.1.8"
          sources."@material/layout-grid-0.1.1"
          (sources."@material/list-0.2.6" // {
            dependencies = [
              sources."@material/rtl-0.1.3"
            ];
          })
          sources."@material/menu-0.2.3"
          sources."@material/radio-0.2.1"
          sources."@material/ripple-0.5.1"
          (sources."@material/select-0.3.3" // {
            dependencies = [
              sources."@material/rtl-0.1.3"
            ];
          })
          (sources."@material/snackbar-0.1.8" // {
            dependencies = [
              sources."@material/rtl-0.1.3"
            ];
          })
          sources."@material/switch-0.1.4"
          (sources."@material/textfield-0.2.6" // {
            dependencies = [
              sources."@material/rtl-0.1.3"
            ];
          })
          sources."@material/theme-0.1.4"
          (sources."@material/toolbar-0.2.2" // {
            dependencies = [
              sources."@material/rtl-0.1.3"
            ];
          })
          sources."@material/typography-0.2.1"
        ];
      })
      sources."material-design-icons-3.0.1"
      sources."roboto-fontface-0.7.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "BSD3";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}