# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@material/animation-1.0.0" = {
      name = "_at_material_slash_animation";
      packageName = "@material/animation";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/animation/-/animation-1.0.0.tgz";
        sha512 = "Ed5/vggn6ZhSJ87yn3ZS1d826VJNFz73jHF2bSsgRtHDoB8KCuOwQMfdgAgDa4lKDF6CDIPCKBZPKrs2ubehdw==";
      };
    };
    "@material/auto-init-1.0.0" = {
      name = "_at_material_slash_auto-init";
      packageName = "@material/auto-init";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/auto-init/-/auto-init-1.0.0.tgz";
        sha512 = "xlWEjjyQquXMi9xz3RH7HW/5dsLGkVYQnm1WCYw2a6JIpIlipkkLEzBNc//agiQongIBbLndL07gO7WQeSohNA==";
      };
    };
    "@material/base-1.0.0" = {
      name = "_at_material_slash_base";
      packageName = "@material/base";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/base/-/base-1.0.0.tgz";
        sha512 = "5dxFp46x5FA+Epg6YHLzN+5zRt9S2wR84UdvVAEJ1egea94m9UHUg7y9tAnNSN16aexRSywmzyLwPr+i8PGEYA==";
      };
    };
    "@material/button-1.1.0" = {
      name = "_at_material_slash_button";
      packageName = "@material/button";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/button/-/button-1.1.0.tgz";
        sha512 = "P1oZyyC1ELRe26vdnmax+fO3BWNmftDqHDDlQbJ+gfYMDQsNQtZNJU16ZbnVHsnzEXOpFj729imbmuLfnz8Nbg==";
      };
    };
    "@material/card-1.1.0" = {
      name = "_at_material_slash_card";
      packageName = "@material/card";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/card/-/card-1.1.0.tgz";
        sha512 = "ZuzMwnFZx0qMTiQK/QHoEClsOQ8TbfIpYm1N5gVvnGgbLF6xxoLD2zZFS9/l3eJxrDOxsrqqgxxfjGlJB5dFRg==";
      };
    };
    "@material/checkbox-1.1.0" = {
      name = "_at_material_slash_checkbox";
      packageName = "@material/checkbox";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/checkbox/-/checkbox-1.1.0.tgz";
        sha512 = "jCrkG8VkN63uH+YRhu7RWIsrYGw2Gu89OEPe+sqGYWsr+BbOuzBBqxrM09rUkXykCyi8gAbxpWZPVGCmcDHtJQ==";
      };
    };
    "@material/chips-1.1.0" = {
      name = "_at_material_slash_chips";
      packageName = "@material/chips";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/chips/-/chips-1.1.0.tgz";
        sha512 = "+cIscrfKBFhXMaOHgNWx46U7zctXX6toMMG9lxY+uqH9ALo/NeScdZp/kc0C3z0shvRzXjZfvl5rM28rKjnizw==";
      };
    };
    "@material/dialog-1.1.0" = {
      name = "_at_material_slash_dialog";
      packageName = "@material/dialog";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/dialog/-/dialog-1.1.0.tgz";
        sha512 = "XbFTTdzzRhjClLMDFxz8SR/mwwCBpQL6N7Z7UzX7SgD51UJmd19SsXPItFquRKk3mkNuoFBBcR4KJ6julAW+Fg==";
      };
    };
    "@material/dom-1.1.0" = {
      name = "_at_material_slash_dom";
      packageName = "@material/dom";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/dom/-/dom-1.1.0.tgz";
        sha512 = "+HWW38ZaM2UBPu4+7QCusLDSf4tFT31rsEXHkTkxYSg/QpDivfPx6YDz4OmYtafmhPR1d1YjqB3MYysUHdodyw==";
      };
    };
    "@material/drawer-1.1.0" = {
      name = "_at_material_slash_drawer";
      packageName = "@material/drawer";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/drawer/-/drawer-1.1.0.tgz";
        sha512 = "IKQejVv9oSf1sUoAZ7BdV8fhTVDfMfZXfAOQBpw6QyfQujGkNVZatOsvbRcOFPu3naNZFS7brbHRiBH2ArgMQQ==";
      };
    };
    "@material/elevation-1.1.0" = {
      name = "_at_material_slash_elevation";
      packageName = "@material/elevation";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/elevation/-/elevation-1.1.0.tgz";
        sha512 = "m4eATJvDhWK1BT+yA1iHz5mhAk8cV9olC4mjVzm4PTAqhDH2yya4WzjN1HPVHE/a65ObyZ7V4qopxu9MRocm3A==";
      };
    };
    "@material/fab-1.1.0" = {
      name = "_at_material_slash_fab";
      packageName = "@material/fab";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/fab/-/fab-1.1.0.tgz";
        sha512 = "oCvo/4TFri+agTkGvEd5lREuwowInYw6OBbwNmGxpWQs4QGlMGHRS9/h8sfMYNZxs2TrwNUCwf/DK0WZEvniLQ==";
      };
    };
    "@material/feature-targeting-0.44.1" = {
      name = "_at_material_slash_feature-targeting";
      packageName = "@material/feature-targeting";
      version = "0.44.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/feature-targeting/-/feature-targeting-0.44.1.tgz";
        sha512 = "90cc7njn4aHbH9UxY8qgZth1W5JgOgcEdWdubH1t7sFkwqFxS5g3zgxSBt46TygFBVIXNZNq35Xmg80wgqO7Pg==";
      };
    };
    "@material/floating-label-1.1.0" = {
      name = "_at_material_slash_floating-label";
      packageName = "@material/floating-label";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/floating-label/-/floating-label-1.1.0.tgz";
        sha512 = "7q7V+9o9XesgMnK11up9z+BcRFwtLIAIqVTCL3liKRARNHuzw9FGrGMKhTJUKvLZ3z0bM1+FmmVlA3q9FJWehQ==";
      };
    };
    "@material/form-field-1.1.0" = {
      name = "_at_material_slash_form-field";
      packageName = "@material/form-field";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/form-field/-/form-field-1.1.0.tgz";
        sha512 = "/m382G90rctenVAbPwTzAVtQGm9Bjnnvde03WPijFE6kirczi6pJWns+cFtN///e5nUc5fhBwNdpEnJmoUYvQg==";
      };
    };
    "@material/grid-list-1.1.0" = {
      name = "_at_material_slash_grid-list";
      packageName = "@material/grid-list";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/grid-list/-/grid-list-1.1.0.tgz";
        sha512 = "YukGKO4EzJca5DktfcNKCcrE6B3j/0CznCS0yfAoYagGZxsmmxa1wY4BcObuocIP31/xksRMUCieRbWpKzBhBQ==";
      };
    };
    "@material/icon-button-1.1.0" = {
      name = "_at_material_slash_icon-button";
      packageName = "@material/icon-button";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/icon-button/-/icon-button-1.1.0.tgz";
        sha512 = "3HYOfFhlgpY32HyNt1thQJfTycjy0Cfd4B4IZmt2irfaETdj6JuP0wKs9kdEx1VHTbfWFkJHENArz0lPW+6r2A==";
      };
    };
    "@material/image-list-1.1.0" = {
      name = "_at_material_slash_image-list";
      packageName = "@material/image-list";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/image-list/-/image-list-1.1.0.tgz";
        sha512 = "X4ZlrzMbtZ80kkZQQHTR6CJEgBbCuQ3bYcJiXeTYS5jvl7frtiqf7CPkkrAZ4ftaaS/qiJgWMZUz3U5YaaAAsQ==";
      };
    };
    "@material/layout-grid-0.41.0" = {
      name = "_at_material_slash_layout-grid";
      packageName = "@material/layout-grid";
      version = "0.41.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/layout-grid/-/layout-grid-0.41.0.tgz";
        sha512 = "Sa5RNoTGgfIojqJ9E94p7/k11V6q/tGk7HwKi4AQNAPjxield0zcl3G/SbsSb8YSHoK+D+7OXDN+n11x6EqF7g==";
      };
    };
    "@material/line-ripple-1.1.0" = {
      name = "_at_material_slash_line-ripple";
      packageName = "@material/line-ripple";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/line-ripple/-/line-ripple-1.1.0.tgz";
        sha512 = "XqCxDNfgkh9zq0IVlTEFVjmQV8hx8m4vxLFM5qwHDDqcKPlX/Lfc8M43fmm9uE1CaJBC6whMGPvOt/dIla+RUg==";
      };
    };
    "@material/linear-progress-1.1.0" = {
      name = "_at_material_slash_linear-progress";
      packageName = "@material/linear-progress";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/linear-progress/-/linear-progress-1.1.0.tgz";
        sha512 = "MIK0cD/o1rTLREtAfTK3v60h7A0/wAu8/3v9dPTMlAPe+Y5gOarAizYWM3r/bp88sGO4gU8nPK0X9/daD28pNw==";
      };
    };
    "@material/list-1.1.0" = {
      name = "_at_material_slash_list";
      packageName = "@material/list";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/list/-/list-1.1.0.tgz";
        sha512 = "+NqVwqhRX08kjDatwZRO/LiiOw9gl7eq2Ogi8hrWkXqYn9ARfUq3K74MeTIit9f7BGPobs86dXBaQ/mjI5HSXg==";
      };
    };
    "@material/menu-1.1.0" = {
      name = "_at_material_slash_menu";
      packageName = "@material/menu";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/menu/-/menu-1.1.0.tgz";
        sha512 = "oEubeu4h5EWeaOWbDwstmWkzBSq/2qVtu476CLmaAI5joUilXaPBKpryv4F+ZRIDlVQjs5Ey7uBotxDwDELPQA==";
      };
    };
    "@material/menu-surface-1.1.0" = {
      name = "_at_material_slash_menu-surface";
      packageName = "@material/menu-surface";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/menu-surface/-/menu-surface-1.1.0.tgz";
        sha512 = "FjCA6TBgeY+mwNcjfeq5/3TCSyhtXxHrT/xQrz1LyrztuHI4Qu7bTb496pXlfPsZHQuwmo9PqW+pwP78noDf9A==";
      };
    };
    "@material/notched-outline-1.1.0" = {
      name = "_at_material_slash_notched-outline";
      packageName = "@material/notched-outline";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/notched-outline/-/notched-outline-1.1.0.tgz";
        sha512 = "J/MCe3an5lTxzYZPzHxblbVZu51OKeum4BU9PeV9WJW+IBGBAnQmT2uf53rqAzhEchIpv39MYmJLPMJghVxWAg==";
      };
    };
    "@material/radio-1.1.0" = {
      name = "_at_material_slash_radio";
      packageName = "@material/radio";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/radio/-/radio-1.1.0.tgz";
        sha512 = "ySocik+l1fInopaA8hDfByJahv1UywUNtUcG7+hLLOhxQx4XVpUJUIjU/dlvVDYJB0QZQatm2asKi2cYVPlIsQ==";
      };
    };
    "@material/ripple-1.1.0" = {
      name = "_at_material_slash_ripple";
      packageName = "@material/ripple";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/ripple/-/ripple-1.1.0.tgz";
        sha512 = "mkfDBZAmxjpRG7V9TrfOmLxt1g/wvGHCXtYPgvH7W8ozjf53edqxLOFENEdvHbie27y9nyixzXn0gzU0HnxSeA==";
      };
    };
    "@material/rtl-0.42.0" = {
      name = "_at_material_slash_rtl";
      packageName = "@material/rtl";
      version = "0.42.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/rtl/-/rtl-0.42.0.tgz";
        sha512 = "VrnrKJzhmspsN8WXHuxxBZ69yM5IwhCUqWr1t1eNfw3ZEvEj7i1g3P31HGowKThIN1dc1Wh4LE14rCISWCtv5w==";
      };
    };
    "@material/select-1.1.0" = {
      name = "_at_material_slash_select";
      packageName = "@material/select";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/select/-/select-1.1.0.tgz";
        sha512 = "sl5dt+sepqfo4HC82085q9sSCaXoK1swmeQ54Yp8KWlit9CtfV4/QZT83NwF9eEbQF3NmtCdh9T2ueaX//uihg==";
      };
    };
    "@material/shape-1.0.0" = {
      name = "_at_material_slash_shape";
      packageName = "@material/shape";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/shape/-/shape-1.0.0.tgz";
        sha512 = "zfXEacPQZmH+ujVtaFyfAsYiF46j1QCcFzJeZVouG4pznrbA7XD6614Ywg0wbyWX5iB6hD52ld/IN+R/6oxKqA==";
      };
    };
    "@material/slider-1.1.0" = {
      name = "_at_material_slash_slider";
      packageName = "@material/slider";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/slider/-/slider-1.1.0.tgz";
        sha512 = "JV/Phpt38LUVb2sQCr2pBsf0faw0E5LI7ag3dNF3hDq1f3F9Vcu+a8oNADi2M+TNlyelltAMKnc9guARwhDLKw==";
      };
    };
    "@material/snackbar-1.1.0" = {
      name = "_at_material_slash_snackbar";
      packageName = "@material/snackbar";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/snackbar/-/snackbar-1.1.0.tgz";
        sha512 = "gPTvAg/Djzz2FHVruGNvdvOkNoeZPctc1hasksBmJPHhQ0nQtc3JsRPfNTLAy32k8aF2+JlrEa1YGMAnltkuPA==";
      };
    };
    "@material/switch-1.1.0" = {
      name = "_at_material_slash_switch";
      packageName = "@material/switch";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/switch/-/switch-1.1.0.tgz";
        sha512 = "hwgPzMgZksmJB/hOHQqrT7SZ6TpYaBtkW6BDhCojluBzaMDfDZxeXbNAhAYCO+tJI9p+CndPF+InsocCQDAJXA==";
      };
    };
    "@material/tab-1.1.0" = {
      name = "_at_material_slash_tab";
      packageName = "@material/tab";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/tab/-/tab-1.1.0.tgz";
        sha512 = "62uttUJURFM36AmXNSrH5ewxJJv632pryEXllpBB1WCHYv6QqRwgfQ6dTjE5xdgSa4k+1X2BJCgmD/0ghc233A==";
      };
    };
    "@material/tab-bar-1.1.0" = {
      name = "_at_material_slash_tab-bar";
      packageName = "@material/tab-bar";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/tab-bar/-/tab-bar-1.1.0.tgz";
        sha512 = "uhtIRiyOvBVMZ5Wf6QctPfI/amXfWR9sXjHpYj+So6GPRNgmeQFkRJ1yyxU3KthBoyzfLvj57sgWEsBlSkiJzw==";
      };
    };
    "@material/tab-indicator-1.1.0" = {
      name = "_at_material_slash_tab-indicator";
      packageName = "@material/tab-indicator";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/tab-indicator/-/tab-indicator-1.1.0.tgz";
        sha512 = "wbZMFCfQo62einr/Ju9PDAeFpRR/Ori5oV2lcsF1uSQXeLxougarwcbk0egWnEtY4Wa6dPgM5P6wQQsYnIeUIQ==";
      };
    };
    "@material/tab-scroller-1.1.0" = {
      name = "_at_material_slash_tab-scroller";
      packageName = "@material/tab-scroller";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/tab-scroller/-/tab-scroller-1.1.0.tgz";
        sha512 = "o5AuG8kwZaghuZ4kvYXIsp2tp3plHoGArF5wM7UgERk+8vMeMRmanagnpYvFwrtGgsta8EQa9sKVZ90dMIDZvg==";
      };
    };
    "@material/textfield-1.1.0" = {
      name = "_at_material_slash_textfield";
      packageName = "@material/textfield";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/textfield/-/textfield-1.1.0.tgz";
        sha512 = "3+vFrWGVrGxvP4ICsniS8Sn9HHRaBz+/EZgpPnsYRcE0LcE2ABjUlwZQzeHV1h1qc0XmulmLUon8WFGvTxISkA==";
      };
    };
    "@material/theme-1.1.0" = {
      name = "_at_material_slash_theme";
      packageName = "@material/theme";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/theme/-/theme-1.1.0.tgz";
        sha512 = "YYUV9Rhbx4r/EMb/zoOYJUWjhXChNaLlH1rqt3vpNVyxRcxGqoVMGp5u1XALBCFiD9dACPKLIkKyRYa928nmPQ==";
      };
    };
    "@material/toolbar-1.1.0" = {
      name = "_at_material_slash_toolbar";
      packageName = "@material/toolbar";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/toolbar/-/toolbar-1.1.0.tgz";
        sha512 = "NrO3Z1YH6AGbLjS91BT4BTaUL1ghXHB0Wrre+rT1mmQ7VXtr+AaTSshu9xc7z3wcVuPotR41OOdZqSCDWjzBrg==";
      };
    };
    "@material/top-app-bar-1.1.0" = {
      name = "_at_material_slash_top-app-bar";
      packageName = "@material/top-app-bar";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/top-app-bar/-/top-app-bar-1.1.0.tgz";
        sha512 = "fxVKFolNzPG4+LqH8GUxDKfjRZtQNDYX8sGD6c2pKbk1tigyiAGBO/Py31RQQkbAdCKPdmnanGJK2gewaUdw4g==";
      };
    };
    "@material/typography-1.0.0" = {
      name = "_at_material_slash_typography";
      packageName = "@material/typography";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/typography/-/typography-1.0.0.tgz";
        sha512 = "Oeqbjci1cC7jTE8/n3dwnkqKe9ZeWiaE+rgMtRYtRFw1HvAw14SpGA5EEAS/Li2Hu2KZ50FYCe3HYqShfxtChA==";
      };
    };
    "focus-trap-4.0.2" = {
      name = "focus-trap";
      packageName = "focus-trap";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/focus-trap/-/focus-trap-4.0.2.tgz";
        sha512 = "HtLjfAK7Hp2qbBtLS6wEznID1mPT+48ZnP2nkHzgjpL4kroYHg0CdqJ5cTXk+UO5znAxF5fRUkhdyfgrhh8Lzw==";
      };
    };
    "material-components-web-1.1.0" = {
      name = "material-components-web";
      packageName = "material-components-web";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/material-components-web/-/material-components-web-1.1.0.tgz";
        sha512 = "bTivBr0oZUfw9N32G/PVZ4RRzH8ge7V8CXlGblVB4WE1HJQU5FVgp7cN1z5vYQhEGOCtyT0VlHjzWvOWKMDxFg==";
      };
    };
    "material-design-icons-3.0.1" = {
      name = "material-design-icons";
      packageName = "material-design-icons";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/material-design-icons/-/material-design-icons-3.0.1.tgz";
        sha1 = "9a71c48747218ebca51e51a66da682038cdcb7bf";
      };
    };
    "roboto-fontface-0.10.0" = {
      name = "roboto-fontface";
      packageName = "roboto-fontface";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/roboto-fontface/-/roboto-fontface-0.10.0.tgz";
        sha512 = "OlwfYEgA2RdboZohpldlvJ1xngOins5d7ejqnIBWr9KaMxsnBqotpptRXTyfNRLnFpqzX6sTDt+X+a+6udnU8g==";
      };
    };
    "tabbable-3.1.2" = {
      name = "tabbable";
      packageName = "tabbable";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tabbable/-/tabbable-3.1.2.tgz";
        sha512 = "wjB6puVXTYO0BSFtCmWQubA/KIn7Xvajw0x0l6eJUudMG/EAiJvIUnyNX6xO4NpGrJ16lbD0eUseB9WxW0vlpQ==";
      };
    };
    "tslib-1.9.3" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.9.3.tgz";
        sha512 = "4krF8scpejhaOgqzBEcGM7yDIEfi0/8+8zDRZhNZZ2kjmHJ4hv3zCbQWxoJGz1iw5U0Jl0nma13xzHXcncMavQ==";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
  };
  args = {
    name = "reflex-material";
    packageName = "reflex-material";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@material/animation-1.0.0"
      sources."@material/auto-init-1.0.0"
      sources."@material/base-1.0.0"
      sources."@material/button-1.1.0"
      sources."@material/card-1.1.0"
      sources."@material/checkbox-1.1.0"
      sources."@material/chips-1.1.0"
      sources."@material/dialog-1.1.0"
      sources."@material/dom-1.1.0"
      sources."@material/drawer-1.1.0"
      sources."@material/elevation-1.1.0"
      sources."@material/fab-1.1.0"
      sources."@material/feature-targeting-0.44.1"
      sources."@material/floating-label-1.1.0"
      sources."@material/form-field-1.1.0"
      sources."@material/grid-list-1.1.0"
      sources."@material/icon-button-1.1.0"
      sources."@material/image-list-1.1.0"
      sources."@material/layout-grid-0.41.0"
      sources."@material/line-ripple-1.1.0"
      sources."@material/linear-progress-1.1.0"
      sources."@material/list-1.1.0"
      sources."@material/menu-1.1.0"
      sources."@material/menu-surface-1.1.0"
      sources."@material/notched-outline-1.1.0"
      sources."@material/radio-1.1.0"
      sources."@material/ripple-1.1.0"
      sources."@material/rtl-0.42.0"
      sources."@material/select-1.1.0"
      sources."@material/shape-1.0.0"
      sources."@material/slider-1.1.0"
      sources."@material/snackbar-1.1.0"
      sources."@material/switch-1.1.0"
      sources."@material/tab-1.1.0"
      sources."@material/tab-bar-1.1.0"
      sources."@material/tab-indicator-1.1.0"
      sources."@material/tab-scroller-1.1.0"
      sources."@material/textfield-1.1.0"
      sources."@material/theme-1.1.0"
      sources."@material/toolbar-1.1.0"
      sources."@material/top-app-bar-1.1.0"
      sources."@material/typography-1.0.0"
      sources."focus-trap-4.0.2"
      sources."material-components-web-1.1.0"
      sources."material-design-icons-3.0.1"
      sources."roboto-fontface-0.10.0"
      sources."tabbable-3.1.2"
      sources."tslib-1.9.3"
      sources."xtend-4.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "BSD3";
    };
    production = true;
    bypassCache = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}