# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@material/animation-0.1.5" = {
      name = "_at_material_slash_animation";
      packageName = "@material/animation";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/animation/-/animation-0.1.5.tgz";
        sha1 = "79c45ccdcde8a286a4c3d7955873b2079e4e5c32";
      };
    };
    "@material/animation-0.2.3" = {
      name = "_at_material_slash_animation";
      packageName = "@material/animation";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/animation/-/animation-0.2.3.tgz";
        sha1 = "25f24962cd649e76459a16ab234b7846a7a7f419";
      };
    };
    "@material/animation-0.3.1" = {
      name = "_at_material_slash_animation";
      packageName = "@material/animation";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/animation/-/animation-0.3.1.tgz";
        sha1 = "229de6927d0590d6d6b20157d778d264ef02229a";
      };
    };
    "@material/animation-0.4.1" = {
      name = "_at_material_slash_animation";
      packageName = "@material/animation";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/animation/-/animation-0.4.1.tgz";
        sha1 = "bf8b50aedad4cffce8a5b428fdca8f1abbaf176e";
      };
    };
    "@material/auto-init-0.1.4" = {
      name = "_at_material_slash_auto-init";
      packageName = "@material/auto-init";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/auto-init/-/auto-init-0.1.4.tgz";
        sha512 = "pyq6hTVrYo/Z/yU3vCAaIpo7C9As/Inj49kt7tRPLsCQ5MDhhMTjCZFmqldDss88XQ1QR2gjNoSh7lNkwRlu7A==";
      };
    };
    "@material/base-0.1.3" = {
      name = "_at_material_slash_base";
      packageName = "@material/base";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/base/-/base-0.1.3.tgz";
        sha1 = "f58f60f5164df4d0eaec70730908b02255f76dcd";
      };
    };
    "@material/base-0.2.6" = {
      name = "_at_material_slash_base";
      packageName = "@material/base";
      version = "0.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/base/-/base-0.2.6.tgz";
        sha1 = "3003f3df2c06d172151d4160b8c8b2e6c65e7c01";
      };
    };
    "@material/button-0.3.11" = {
      name = "_at_material_slash_button";
      packageName = "@material/button";
      version = "0.3.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/button/-/button-0.3.11.tgz";
        sha1 = "17ab4cd5d55389e3da3496b1c1626dce4f6a7839";
      };
    };
    "@material/card-0.1.8" = {
      name = "_at_material_slash_card";
      packageName = "@material/card";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/card/-/card-0.1.8.tgz";
        sha1 = "e13a63b256c45a5bada40e33d786ba766d5c73ca";
      };
    };
    "@material/checkbox-0.3.7" = {
      name = "_at_material_slash_checkbox";
      packageName = "@material/checkbox";
      version = "0.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/checkbox/-/checkbox-0.3.7.tgz";
        sha1 = "512cb48641f0c9d69af644550e4edefae7294aac";
      };
    };
    "@material/dialog-0.2.4" = {
      name = "_at_material_slash_dialog";
      packageName = "@material/dialog";
      version = "0.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/dialog/-/dialog-0.2.4.tgz";
        sha1 = "873863388f4deedb246d108d8cea7650d318e580";
      };
    };
    "@material/drawer-0.3.1" = {
      name = "_at_material_slash_drawer";
      packageName = "@material/drawer";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/drawer/-/drawer-0.3.1.tgz";
        sha1 = "ae3137e34ecf87f7d8a58e2bc11e88d06e667e80";
      };
    };
    "@material/elevation-0.1.13" = {
      name = "_at_material_slash_elevation";
      packageName = "@material/elevation";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/elevation/-/elevation-0.1.13.tgz";
        sha1 = "a38885f3caf4398ca6a7468c308887d70bd4605b";
      };
    };
    "@material/fab-0.3.16" = {
      name = "_at_material_slash_fab";
      packageName = "@material/fab";
      version = "0.3.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/fab/-/fab-0.3.16.tgz";
        sha512 = "xiLEi6L7Ethhr/MJYfW/d6yMSNt7wBHswhZ+GOPBb/MQ7ODT6mSPknoNx9pE2IlQNdEY27+spijTcEpERzzJZg==";
      };
    };
    "@material/form-field-0.2.17" = {
      name = "_at_material_slash_form-field";
      packageName = "@material/form-field";
      version = "0.2.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/form-field/-/form-field-0.2.17.tgz";
        sha1 = "7e2a268495160712c0d96d44530820098a5dca55";
      };
    };
    "@material/grid-list-0.2.13" = {
      name = "_at_material_slash_grid-list";
      packageName = "@material/grid-list";
      version = "0.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/grid-list/-/grid-list-0.2.13.tgz";
        sha1 = "04ce198d23c710c67316f1ec5f0409829fd6bead";
      };
    };
    "@material/icon-toggle-0.1.22" = {
      name = "_at_material_slash_icon-toggle";
      packageName = "@material/icon-toggle";
      version = "0.1.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/icon-toggle/-/icon-toggle-0.1.22.tgz";
        sha1 = "c6c449851f6b9ed29ff3799ee55a3410809b890f";
      };
    };
    "@material/layout-grid-0.1.2" = {
      name = "_at_material_slash_layout-grid";
      packageName = "@material/layout-grid";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/layout-grid/-/layout-grid-0.1.2.tgz";
        sha1 = "c19d69e3a8ff9f0949528e1c7fe2ab4fda492c7b";
      };
    };
    "@material/list-0.2.20" = {
      name = "_at_material_slash_list";
      packageName = "@material/list";
      version = "0.2.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/list/-/list-0.2.20.tgz";
        sha1 = "5ed4b31be3b19c1ac5c2f45b8bd8885bb5737434";
      };
    };
    "@material/menu-0.2.7" = {
      name = "_at_material_slash_menu";
      packageName = "@material/menu";
      version = "0.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/menu/-/menu-0.2.7.tgz";
        sha1 = "8e7c43b28d77160efd97eed17b6b2dd37b320aab";
      };
    };
    "@material/menu-0.4.8" = {
      name = "_at_material_slash_menu";
      packageName = "@material/menu";
      version = "0.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/menu/-/menu-0.4.8.tgz";
        sha1 = "603b4005d96970e15474f9d2823f4c7ca0f5287b";
      };
    };
    "@material/radio-0.2.15" = {
      name = "_at_material_slash_radio";
      packageName = "@material/radio";
      version = "0.2.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/radio/-/radio-0.2.15.tgz";
        sha1 = "3598f79cbe1c413c2b54ac32b0db12955f93636b";
      };
    };
    "@material/ripple-0.5.1" = {
      name = "_at_material_slash_ripple";
      packageName = "@material/ripple";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/ripple/-/ripple-0.5.1.tgz";
        sha1 = "b361f10d30fd4e6e1db9c5234a0dac32dfe35ce6";
      };
    };
    "@material/ripple-0.6.2" = {
      name = "_at_material_slash_ripple";
      packageName = "@material/ripple";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/ripple/-/ripple-0.6.2.tgz";
        sha1 = "a8556db7c141d35f5582c5990be8690bef9dee59";
      };
    };
    "@material/ripple-0.7.0" = {
      name = "_at_material_slash_ripple";
      packageName = "@material/ripple";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/ripple/-/ripple-0.7.0.tgz";
        sha1 = "ea784a6c54f8d493d3df21440dcfaba706fb0caa";
      };
    };
    "@material/ripple-0.8.8" = {
      name = "_at_material_slash_ripple";
      packageName = "@material/ripple";
      version = "0.8.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/ripple/-/ripple-0.8.8.tgz";
        sha1 = "22b89ed9e63883f17fa4f00d12370e32e0c459b7";
      };
    };
    "@material/rtl-0.1.8" = {
      name = "_at_material_slash_rtl";
      packageName = "@material/rtl";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/rtl/-/rtl-0.1.8.tgz";
        sha512 = "NzBobwxvhJg+dch99pVO+Z9HL1DM+esuIy5WYXgM7trfOVh8n9DkVo5vD/NKnDy6F5wCaRnJOI5T19Tev6c9Zw==";
      };
    };
    "@material/select-0.3.18" = {
      name = "_at_material_slash_select";
      packageName = "@material/select";
      version = "0.3.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/select/-/select-0.3.18.tgz";
        sha1 = "6301de3c77ae749edeedb97dd236b55b30c0a332";
      };
    };
    "@material/selection-control-0.1.3" = {
      name = "_at_material_slash_selection-control";
      packageName = "@material/selection-control";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/selection-control/-/selection-control-0.1.3.tgz";
        sha1 = "4fb7ed1fd7ee2296a32c156cf2c1eb892bfe44c6";
      };
    };
    "@material/snackbar-0.1.11" = {
      name = "_at_material_slash_snackbar";
      packageName = "@material/snackbar";
      version = "0.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/snackbar/-/snackbar-0.1.11.tgz";
        sha1 = "065fa03bfe259232276b2b715c9532242ae2341a";
      };
    };
    "@material/switch-0.1.15" = {
      name = "_at_material_slash_switch";
      packageName = "@material/switch";
      version = "0.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/switch/-/switch-0.1.15.tgz";
        sha1 = "6f2b1f1ef7c3dc96e32a68a3101498b562914619";
      };
    };
    "@material/textfield-0.2.11" = {
      name = "_at_material_slash_textfield";
      packageName = "@material/textfield";
      version = "0.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/textfield/-/textfield-0.2.11.tgz";
        sha512 = "k82nLd9H0QFLHYL6f/KKL0DnJakKXSCVm0G7zqU3t+7TaHqgIzHwHvLsSULtsCaIkKjlxXHTBeZmLv7DegH1Zg==";
      };
    };
    "@material/theme-0.1.7" = {
      name = "_at_material_slash_theme";
      packageName = "@material/theme";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/theme/-/theme-0.1.7.tgz";
        sha1 = "d94a7c5099feae9dc318c639802327c7ae82e872";
      };
    };
    "@material/theme-0.2.0" = {
      name = "_at_material_slash_theme";
      packageName = "@material/theme";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/theme/-/theme-0.2.0.tgz";
        sha512 = "JImkTjEPt6LxjU3eTeZQSZVZfCs8ooCC8nYk736bB3IRMYSJCsX5EZ+ZoEehtqRpS++VLQID3raWdGUy2kNJzA==";
      };
    };
    "@material/theme-0.4.0" = {
      name = "_at_material_slash_theme";
      packageName = "@material/theme";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/theme/-/theme-0.4.0.tgz";
        sha1 = "0aef1a0279b65c15990584fb8b8eca095c734641";
      };
    };
    "@material/toolbar-0.2.2" = {
      name = "_at_material_slash_toolbar";
      packageName = "@material/toolbar";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/toolbar/-/toolbar-0.2.2.tgz";
        sha1 = "1d87d6ba4e5d6cd0010031c151d9f29b5ec949ed";
      };
    };
    "@material/typography-0.1.1" = {
      name = "_at_material_slash_typography";
      packageName = "@material/typography";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/typography/-/typography-0.1.1.tgz";
        sha1 = "fb2e3437bd3284d39e9fb91485767ade6b2bd0c1";
      };
    };
    "@material/typography-0.2.3" = {
      name = "_at_material_slash_typography";
      packageName = "@material/typography";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/typography/-/typography-0.2.3.tgz";
        sha1 = "cddf4178098c9c7b4c2e78a33049376b4d6aeb53";
      };
    };
    "@material/typography-0.3.0" = {
      name = "_at_material_slash_typography";
      packageName = "@material/typography";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/typography/-/typography-0.3.0.tgz";
        sha1 = "f828c2d3215bfd66c58072709b4260c64125390a";
      };
    };
    "focus-trap-2.4.6" = {
      name = "focus-trap";
      packageName = "focus-trap";
      version = "2.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/focus-trap/-/focus-trap-2.4.6.tgz";
        sha512 = "vWZTPtBU6pBoyWZDRZJHkXsyP2ZCZBHE3DRVXnSVdQKH/mcDtu9S5Kz8CUDyIqpfZfLEyI9rjKJLnc4Y40BRBg==";
      };
    };
    "material-components-web-0.9.1" = {
      name = "material-components-web";
      packageName = "material-components-web";
      version = "0.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/material-components-web/-/material-components-web-0.9.1.tgz";
        sha1 = "052d02c81f1af2a361568ae95d232e3efd8b6345";
      };
    };
    "material-design-icons-3.0.1" = {
      name = "material-design-icons";
      packageName = "material-design-icons";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/material-design-icons/-/material-design-icons-3.0.1.tgz";
        sha1 = "9a71c48747218ebca51e51a66da682038cdcb7bf";
      };
    };
    "roboto-fontface-0.7.1" = {
      name = "roboto-fontface";
      packageName = "roboto-fontface";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/roboto-fontface/-/roboto-fontface-0.7.1.tgz";
        sha512 = "nMrOlRrGc1lHfIgW1kpw7IYh0EZ98YZtNA5aSKbVBL4y+1DfqASRkB2qB4/5f1yM4gn7sPtMjLgXngUe4mqR9Q==";
      };
    };
    "tabbable-1.1.3" = {
      name = "tabbable";
      packageName = "tabbable";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tabbable/-/tabbable-1.1.3.tgz";
        sha512 = "nOWwx35/JuDI4ONuF0ZTo6lYvI0fY0tZCH1ErzY2EXfu4az50ZyiUX8X073FLiZtmWUVlkRnuXsehjJgCw9tYg==";
      };
    };
  };
  args = {
    name = "reflex-material";
    packageName = "reflex-material";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@material/animation-0.1.5"
      sources."@material/auto-init-0.1.4"
      sources."@material/base-0.1.3"
      (sources."@material/button-0.3.11" // {
        dependencies = [
          sources."@material/base-0.2.6"
          (sources."@material/ripple-0.8.8" // {
            dependencies = [
              sources."@material/theme-0.4.0"
            ];
          })
          sources."@material/typography-0.3.0"
        ];
      })
      sources."@material/card-0.1.8"
      (sources."@material/checkbox-0.3.7" // {
        dependencies = [
          sources."@material/animation-0.2.3"
          sources."@material/base-0.2.6"
          sources."@material/ripple-0.7.0"
        ];
      })
      (sources."@material/dialog-0.2.4" // {
        dependencies = [
          sources."@material/animation-0.2.3"
          (sources."@material/ripple-0.6.2" // {
            dependencies = [
              sources."@material/base-0.2.6"
            ];
          })
          sources."@material/typography-0.1.1"
        ];
      })
      sources."@material/drawer-0.3.1"
      (sources."@material/elevation-0.1.13" // {
        dependencies = [
          sources."@material/animation-0.4.1"
        ];
      })
      (sources."@material/fab-0.3.16" // {
        dependencies = [
          sources."@material/animation-0.3.1"
          sources."@material/base-0.2.6"
          (sources."@material/ripple-0.8.8" // {
            dependencies = [
              sources."@material/theme-0.4.0"
            ];
          })
          sources."@material/theme-0.2.0"
        ];
      })
      (sources."@material/form-field-0.2.17" // {
        dependencies = [
          sources."@material/base-0.2.6"
          sources."@material/theme-0.4.0"
          sources."@material/typography-0.3.0"
        ];
      })
      (sources."@material/grid-list-0.2.13" // {
        dependencies = [
          sources."@material/base-0.2.6"
          sources."@material/theme-0.4.0"
          sources."@material/typography-0.3.0"
        ];
      })
      (sources."@material/icon-toggle-0.1.22" // {
        dependencies = [
          sources."@material/animation-0.4.1"
          sources."@material/base-0.2.6"
          sources."@material/ripple-0.8.8"
          sources."@material/theme-0.4.0"
        ];
      })
      sources."@material/layout-grid-0.1.2"
      (sources."@material/list-0.2.20" // {
        dependencies = [
          sources."@material/base-0.2.6"
          sources."@material/ripple-0.8.8"
          sources."@material/theme-0.4.0"
          sources."@material/typography-0.3.0"
        ];
      })
      (sources."@material/menu-0.2.7" // {
        dependencies = [
          sources."@material/animation-0.2.3"
          sources."@material/base-0.2.6"
        ];
      })
      (sources."@material/radio-0.2.15" // {
        dependencies = [
          sources."@material/animation-0.4.1"
          sources."@material/base-0.2.6"
          sources."@material/ripple-0.8.8"
          sources."@material/theme-0.4.0"
        ];
      })
      sources."@material/ripple-0.5.1"
      sources."@material/rtl-0.1.8"
      (sources."@material/select-0.3.18" // {
        dependencies = [
          sources."@material/animation-0.4.1"
          sources."@material/base-0.2.6"
          sources."@material/menu-0.4.8"
          sources."@material/theme-0.4.0"
          sources."@material/typography-0.3.0"
        ];
      })
      (sources."@material/selection-control-0.1.3" // {
        dependencies = [
          sources."@material/base-0.2.6"
          sources."@material/ripple-0.8.8"
          sources."@material/theme-0.4.0"
        ];
      })
      (sources."@material/snackbar-0.1.11" // {
        dependencies = [
          sources."@material/animation-0.2.3"
        ];
      })
      (sources."@material/switch-0.1.15" // {
        dependencies = [
          sources."@material/animation-0.4.1"
          sources."@material/theme-0.4.0"
        ];
      })
      (sources."@material/textfield-0.2.11" // {
        dependencies = [
          sources."@material/animation-0.2.3"
          sources."@material/base-0.2.6"
        ];
      })
      sources."@material/theme-0.1.7"
      sources."@material/toolbar-0.2.2"
      sources."@material/typography-0.2.3"
      sources."focus-trap-2.4.6"
      sources."material-components-web-0.9.1"
      sources."material-design-icons-3.0.1"
      sources."roboto-fontface-0.7.1"
      sources."tabbable-1.1.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "BSD3";
    };
    production = true;
    bypassCache = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}